version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080
    tty: true
    container_name: app

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    networks:
      - default
    tty: true
    container_name: mysql

networks:
  default:
volumes:
  mysql_data:
